version: '3.9'

services:

  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "1080:80"

  my_service_v1:
    container_name: my_service_v1
    build: ./docker/my-service
    ports:
      - "1081:80"
    environment:
      - VERSION=v1

  my_service_v2:
    container_name: my_service_v2
    build: ./docker/my-service
    ports:
      - "1082:80"
    environment:
      - VERSION=v2
