# This is an OpenAPI Specification (https://swagger.io/specification/)
# for multiple-container-versions-poc owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'multiple-container-versions-poc'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    Add a fully fledged description here with markdown syntax.
  contact:
    name: 'multiple-container-versions-poc API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/multiple-container-versions-poc'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/multiple-container-versions-poc'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/multiple-container-versions-poc'
    description: Production environment.
paths: {}
